In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [2]:
dataset = pd.read_csv('ai_jobs_salaries_clean.csv')
dataset.head(5)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,experience_level_label,employment_type_label,work_mode,salary_outlier_flag,role_family,isco_group_hint
0,2025,EX,FT,Head of Data,348516,USD,348516,US,0,US,M,Executive-level,Full-time,On-site,True,Analytics Manager,Information and communications technology serv...
1,2025,EX,FT,Head of Data,232344,USD,232344,US,0,US,M,Executive-level,Full-time,On-site,False,Analytics Manager,Information and communications technology serv...
2,2025,SE,FT,Data Scientist,145400,USD,145400,US,0,US,M,Senior-level,Full-time,On-site,False,Data Scientist,"Mathematicians, actuaries and statisticians"
3,2025,SE,FT,Data Scientist,81600,USD,81600,US,0,US,M,Senior-level,Full-time,On-site,False,Data Scientist,"Mathematicians, actuaries and statisticians"
4,2025,MI,FT,Engineer,160000,USD,160000,US,100,US,M,Mid-level,Full-time,Remote,False,Other / Unclassified,NaN

In [3]:
dataset['High_Salary'] = (dataset['salary_in_usd'] >= 150000).astype(int)

leak_cols = [
    'High_Salary',
    'salary',
    'salary_currency',
    'salary_in_usd',
    'salary_outlier_flag',
]

In [4]:
print(dataset.isnull().sum())

work_year                     0
experience_level              0
employment_type               0
job_title                     0
salary                        0
salary_currency               0
salary_in_usd                 0
employee_residence            0
remote_ratio                  0
company_location              0
company_size                  0
experience_level_label        0
employment_type_label         0
work_mode                     0
salary_outlier_flag           0
role_family                   0
isco_group_hint           40540
High_Salary                   0
dtype: int64

In [5]:
dataset = dataset.dropna()

In [6]:
datatrain, datatest = train_test_split(dataset, test_size=0.2, shuffle=True)

In [7]:
X_train = datatrain.drop(columns=leak_cols)
y_train = datatrain['High_Salary']
X_test = datatest.drop(columns=leak_cols)
y_test = datatest['High_Salary']

In [8]:
X_train.head(5)

,work_year,experience_level,employment_type,job_title,employee_residence,remote_ratio,company_location,company_size,experience_level_label,employment_type_label,work_mode,role_family,isco_group_hint
59573,2024,SE,FT,Data Engineer,GB,0,GB,M,Senior-level,Full-time,On-site,Data Engineer,Software and applications developers
68156,2023,SE,FT,Data Engineer,US,0,US,M,Senior-level,Full-time,On-site,Data Engineer,Software and applications developers
63399,2024,SE,FT,Business Intelligence Analyst,US,100,US,M,Senior-level,Full-time,Remote,Data Analyst,Business services and administration managers
10079,2025,EN,FT,Data Scientist,US,100,US,M,Entry-level,Full-time,Remote,Data Scientist,"Mathematicians, actuaries and statisticians"
69749,2023,SE,FT,Data Scientist,US,0,US,M,Senior-level,Full-time,On-site,Data Scientist,"Mathematicians, actuaries and statisticians"

In [9]:
cols = ['experience_level', 'employment_type', 'job_title', 'employee_residence', 'company_location', 
        'company_size', 'experience_level_label', 'employment_type_label', 'work_mode', 'role_family', 'isco_group_hint']

In [10]:
from catboost import CatBoostClassifier
model = CatBoostClassifier(iterations=2000, cat_features=cols, task_type='GPU')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

Learning rate set to 0.015173
0:	learn: 0.6882222	total: 43.5ms	remaining: 1m 26s
1:	learn: 0.6834636	total: 83.2ms	remaining: 1m 23s
2:	learn: 0.6790251	total: 122ms	remaining: 1m 21s
3:	learn: 0.6746339	total: 162ms	remaining: 1m 20s
4:	learn: 0.6703493	total: 204ms	remaining: 1m 21s
5:	learn: 0.6663763	total: 243ms	remaining: 1m 20s
6:	learn: 0.6623421	total: 284ms	remaining: 1m 20s
7:	learn: 0.6586296	total: 324ms	remaining: 1m 20s
8:	learn: 0.6548641	total: 363ms	remaining: 1m 20s
9:	learn: 0.6513536	total: 405ms	remaining: 1m 20s
10:	learn: 0.6479019	total: 443ms	remaining: 1m 20s
11:	learn: 0.6445176	total: 488ms	remaining: 1m 20s
12:	learn: 0.6413926	total: 527ms	remaining: 1m 20s
13:	learn: 0.6384560	total: 569ms	remaining: 1m 20s
14:	learn: 0.6355138	total: 608ms	remaining: 1m 20s
15:	learn: 0.6327273	total: 651ms	remaining: 1m 20s
16:	learn: 0.6300271	total: 690ms	remaining: 1m 20s
17:	learn: 0.6275423	total: 730ms	remaining: 1m 20s
18:	learn: 0.6251949	total: 771ms	remaining: 1m 20s
19:	learn: 0.6228052	total: 811ms	remaining: 1m 20s
20:	learn: 0.6204568	total: 853ms	remaining: 1m 20s
21:	learn: 0.6184006	total: 893ms	remaining: 1m 20s
22:	learn: 0.6163219	total: 931ms	remaining: 1m 20s
23:	learn: 0.6141439	total: 970ms	remaining: 1m 19s
24:	learn: 0.6120828	total: 1.01s	remaining: 1m 19s
25:	learn: 0.6101315	total: 1.05s	remaining: 1m 19s
26:	learn: 0.6082970	total: 1.09s	remaining: 1m 19s
27:	learn: 0.6065220	total: 1.13s	remaining: 1m 19s
28:	learn: 0.6048451	total: 1.17s	remaining: 1m 19s
29:	learn: 0.6031994	total: 1.21s	remaining: 1m 19s
30:	learn: 0.6014866	total: 1.25s	remaining: 1m 19s
31:	learn: 0.5999409	total: 1.29s	remaining: 1m 19s
32:	learn: 0.5983358	total: 1.33s	remaining: 1m 19s
33:	learn: 0.5968833	total: 1.37s	remaining: 1m 19s
34:	learn: 0.5954360	total: 1.41s	remaining: 1m 19s
35:	learn: 0.5941097	total: 1.45s	remaining: 1m 19s
36:	learn: 0.5928175	total: 1.49s	remaining: 1m 18s
37:	learn: 0.5915284	total: 1.53s	remaining: 1m 18s
38:	learn: 0.5902371	total: 1.57s	remaining: 1m 18s
39:	learn: 0.5891240	total: 1.61s	remaining: 1m 18s
40:	learn: 0.5879484	total: 1.65s	remaining: 1m 18s
41:	learn: 0.5868494	total: 1.69s	remaining: 1m 18s
42:	learn: 0.5857538	total: 1.73s	remaining: 1m 18s
43:	learn: 0.5847180	total: 1.77s	remaining: 1m 18s
44:	learn: 0.5836507	total: 1.82s	remaining: 1m 18s
45:	learn: 0.5826610	total: 1.86s	remaining: 1m 18s
46:	learn: 0.5817714	total: 1.9s	remaining: 1m 18s
47:	learn: 0.5807724	total: 1.93s	remaining: 1m 18s
48:	learn: 0.5799284	total: 1.98s	remaining: 1m 18s
49:	learn: 0.5790823	total: 2.02s	remaining: 1m 18s
50:	learn: 0.5782676	total: 2.06s	remaining: 1m 18s
51:	learn: 0.5773726	total: 2.1s	remaining: 1m 18s
52:	learn: 0.5765331	total: 2.15s	remaining: 1m 18s
53:	learn: 0.5757125	total: 2.19s	remaining: 1m 18s
54:	learn: 0.5749081	total: 2.23s	remaining: 1m 18s
55:	learn: 0.5741723	total: 2.27s	remaining: 1m 18s
56:	learn: 0.5735337	total: 2.31s	remaining: 1m 18s
57:	learn: 0.5728798	total: 2.35s	remaining: 1m 18s
58:	learn: 0.5721971	total: 2.39s	remaining: 1m 18s
59:	learn: 0.5716104	total: 2.43s	remaining: 1m 18s
60:	learn: 0.5710085	total: 2.47s	remaining: 1m 18s
61:	learn: 0.5703750	total: 2.51s	remaining: 1m 18s
62:	learn: 0.5698437	total: 2.55s	remaining: 1m 18s
63:	learn: 0.5693006	total: 2.59s	remaining: 1m 18s
64:	learn: 0.5687727	total: 2.64s	remaining: 1m 18s
65:	learn: 0.5682539	total: 2.68s	remaining: 1m 18s
66:	learn: 0.5676781	total: 2.72s	remaining: 1m 18s
67:	learn: 0.5671816	total: 2.76s	remaining: 1m 18s
68:	learn: 0.5667557	total: 2.8s	remaining: 1m 18s
69:	learn: 0.5662996	total: 2.84s	remaining: 1m 18s
70:	learn: 0.5658770	total: 2.89s	remaining: 1m 18s
71:	learn: 0.5654507	total: 2.93s	remaining: 1m 18s
72:	learn: 0.5650554	total: 2.97s	remaining: 1m 18s
73:	learn: 0.5647016	total: 3.01s	remaining: 1m 18s
74:	learn: 0.5642756	total: 3.05s	remaining: 1m 18s
75:	learn: 0.5639121	total: 3.09s	remaining: 1m 18s
76:	learn: 0.5636040	total: 3.14s	remaining: 1m 18s
77:	learn: 0.5632487	total: 3.18s	remaining: 1m 18s
78:	learn: 0.5629172	total: 3.22s	remaining: 1m 18s
79:	learn: 0.5625798	total: 3.26s	remaining: 1m 18s
80:	learn: 0.5622368	total: 3.31s	remaining: 1m 18s
81:	learn: 0.5619153	total: 3.35s	remaining: 1m 18s
82:	learn: 0.5615729	total: 3.39s	remaining: 1m 18s
83:	learn: 0.5612922	total: 3.43s	remaining: 1m 18s
84:	learn: 0.5610021	total: 3.47s	remaining: 1m 18s
85:	learn: 0.5607452	total: 3.51s	remaining: 1m 18s
86:	learn: 0.5604161	total: 3.55s	remaining: 1m 18s
87:	learn: 0.5601391	total: 3.59s	remaining: 1m 17s
88:	learn: 0.5598340	total: 3.63s	remaining: 1m 17s
89:	learn: 0.5595829	total: 3.67s	remaining: 1m 17s
90:	learn: 0.5593386	total: 3.71s	remaining: 1m 17s
91:	learn: 0.5590502	total: 3.75s	remaining: 1m 17s
92:	learn: 0.5588030	total: 3.78s	remaining: 1m 17s
93:	learn: 0.5585789	total: 3.82s	remaining: 1m 17s
94:	learn: 0.5583414	total: 3.86s	remaining: 1m 17s
95:	learn: 0.5580907	total: 3.9s	remaining: 1m 17s
96:	learn: 0.5578757	total: 3.94s	remaining: 1m 17s
97:	learn: 0.5576620	total: 3.98s	remaining: 1m 17s
98:	learn: 0.5574415	total: 4.02s	remaining: 1m 17s
99:	learn: 0.5572027	total: 4.06s	remaining: 1m 17s
100:	learn: 0.5570005	total: 4.1s	remaining: 1m 17s
101:	learn: 0.5568324	total: 4.14s	remaining: 1m 17s
102:	learn: 0.5566413	total: 4.18s	remaining: 1m 16s
103:	learn: 0.5564564	total: 4.22s	remaining: 1m 16s
104:	learn: 0.5562936	total: 4.26s	remaining: 1m 16s
105:	learn: 0.5560957	total: 4.3s	remaining: 1m 16s
106:	learn: 0.5559159	total: 4.34s	remaining: 1m 16s
107:	learn: 0.5557461	total: 4.38s	remaining: 1m 16s
108:	learn: 0.5555583	total: 4.42s	remaining: 1m 16s
109:	learn: 0.5554002	total: 4.46s	remaining: 1m 16s
110:	learn: 0.5552098	total: 4.5s	remaining: 1m 16s
111:	learn: 0.5550560	total: 4.54s	remaining: 1m 16s
112:	learn: 0.5549289	total: 4.58s	remaining: 1m 16s
113:	learn: 0.5547908	total: 4.62s	remaining: 1m 16s
114:	learn: 0.5546617	total: 4.66s	remaining: 1m 16s
115:	learn: 0.5545336	total: 4.7s	remaining: 1m 16s
116:	learn: 0.5544082	total: 4.74s	remaining: 1m 16s
117:	learn: 0.5542827	total: 4.78s	remaining: 1m 16s
118:	learn: 0.5541308	total: 4.82s	remaining: 1m 16s
119:	learn: 0.5540205	total: 4.86s	remaining: 1m 16s
120:	learn: 0.5539043	total: 4.89s	remaining: 1m 16s
121:	learn: 0.5537960	total: 4.93s	remaining: 1m 15s
122:	learn: 0.5536496	total: 4.98s	remaining: 1m 15s
123:	learn: 0.5535588	total: 5.02s	remaining: 1m 15s
124:	learn: 0.5534398	total: 5.06s	remaining: 1m 15s
125:	learn: 0.5533413	total: 5.1s	remaining: 1m 15s
126:	learn: 0.5532453	total: 5.14s	remaining: 1m 15s
127:	learn: 0.5531126	total: 5.17s	remaining: 1m 15s
128:	learn: 0.5530003	total: 5.21s	remaining: 1m 15s
129:	learn: 0.5529104	total: 5.25s	remaining: 1m 15s
130:	learn: 0.5528300	total: 5.29s	remaining: 1m 15s
131:	learn: 0.5527077	total: 5.33s	remaining: 1m 15s
132:	learn: 0.5526112	total: 5.37s	remaining: 1m 15s
133:	learn: 0.5525252	total: 5.41s	remaining: 1m 15s
134:	learn: 0.5524259	total: 5.45s	remaining: 1m 15s
135:	learn: 0.5523355	total: 5.49s	remaining: 1m 15s
136:	learn: 0.5522397	total: 5.53s	remaining: 1m 15s
137:	learn: 0.5521595	total: 5.58s	remaining: 1m 15s
138:	learn: 0.5520623	total: 5.62s	remaining: 1m 15s
139:	learn: 0.5519912	total: 5.66s	remaining: 1m 15s
140:	learn: 0.5519187	total: 5.69s	remaining: 1m 15s
141:	learn: 0.5518459	total: 5.74s	remaining: 1m 15s
142:	learn: 0.5517575	total: 5.77s	remaining: 1m 14s
143:	learn: 0.5516709	total: 5.81s	remaining: 1m 14s
144:	learn: 0.5515803	total: 5.85s	remaining: 1m 14s
145:	learn: 0.5515157	total: 5.89s	remaining: 1m 14s
146:	learn: 0.5514427	total: 5.93s	remaining: 1m 14s
147:	learn: 0.5513804	total: 5.97s	remaining: 1m 14s
148:	learn: 0.5513232	total: 6.01s	remaining: 1m 14s
149:	learn: 0.5512471	total: 6.05s	remaining: 1m 14s
150:	learn: 0.5511896	total: 6.08s	remaining: 1m 14s
151:	learn: 0.5511139	total: 6.14s	remaining: 1m 14s
152:	learn: 0.5510668	total: 6.18s	remaining: 1m 14s
153:	learn: 0.5509933	total: 6.22s	remaining: 1m 14s
154:	learn: 0.5509392	total: 6.26s	remaining: 1m 14s
155:	learn: 0.5508600	total: 6.3s	remaining: 1m 14s
156:	learn: 0.5508090	total: 6.34s	remaining: 1m 14s
157:	learn: 0.5507576	total: 6.38s	remaining: 1m 14s
158:	learn: 0.5507005	total: 6.42s	remaining: 1m 14s
159:	learn: 0.5506646	total: 6.46s	remaining: 1m 14s
160:	learn: 0.5506222	total: 6.5s	remaining: 1m 14s
161:	learn: 0.5505514	total: 6.54s	remaining: 1m 14s
162:	learn: 0.5505011	total: 6.58s	remaining: 1m 14s
163:	learn: 0.5504411	total: 6.62s	remaining: 1m 14s
164:	learn: 0.5503891	total: 6.66s	remaining: 1m 14s
165:	learn: 0.5503203	total: 6.7s	remaining: 1m 14s
166:	learn: 0.5502721	total: 6.74s	remaining: 1m 14s
167:	learn: 0.5502440	total: 6.78s	remaining: 1m 13s
168:	learn: 0.5501915	total: 6.82s	remaining: 1m 13s
169:	learn: 0.5501409	total: 6.86s	remaining: 1m 13s
170:	learn: 0.5500844	total: 6.9s	remaining: 1m 13s
171:	learn: 0.5500527	total: 6.94s	remaining: 1m 13s
172:	learn: 0.5500015	total: 6.99s	remaining: 1m 13s
173:	learn: 0.5499483	total: 7.03s	remaining: 1m 13s
174:	learn: 0.5498992	total: 7.07s	remaining: 1m 13s
175:	learn: 0.5498469	total: 7.11s	remaining: 1m 13s
176:	learn: 0.5498186	total: 7.15s	remaining: 1m 13s
177:	learn: 0.5497708	total: 7.19s	remaining: 1m 13s
178:	learn: 0.5497210	total: 7.23s	remaining: 1m 13s
179:	learn: 0.5496825	total: 7.27s	remaining: 1m 13s
180:	learn: 0.5496319	total: 7.31s	remaining: 1m 13s
181:	learn: 0.5496036	total: 7.35s	remaining: 1m 13s
182:	learn: 0.5495627	total: 7.39s	remaining: 1m 13s
183:	learn: 0.5495277	total: 7.43s	remaining: 1m 13s
184:	learn: 0.5494955	total: 7.47s	remaining: 1m 13s
185:	learn: 0.5494576	total: 7.51s	remaining: 1m 13s
186:	learn: 0.5494152	total: 7.55s	remaining: 1m 13s
187:	learn: 0.5493844	total: 7.59s	remaining: 1m 13s
188:	learn: 0.5493473	total: 7.63s	remaining: 1m 13s
189:	learn: 0.5493107	total: 7.67s	remaining: 1m 13s
190:	learn: 0.5492649	total: 7.71s	remaining: 1m 13s
191:	learn: 0.5492377	total: 7.75s	remaining: 1m 12s
192:	learn: 0.5491996	total: 7.79s	remaining: 1m 12s
193:	learn: 0.5491563	total: 7.83s	remaining: 1m 12s
194:	learn: 0.5491145	total: 7.87s	remaining: 1m 12s
195:	learn: 0.5490847	total: 7.92s	remaining: 1m 12s
196:	learn: 0.5490503	total: 7.96s	remaining: 1m 12s
197:	learn: 0.5490207	total: 8s	remaining: 1m 12s
198:	learn: 0.5489980	total: 8.04s	remaining: 1m 12s
199:	learn: 0.5489692	total: 8.09s	remaining: 1m 12s
200:	learn: 0.5489362	total: 8.14s	remaining: 1m 12s
201:	learn: 0.5489046	total: 8.18s	remaining: 1m 12s
202:	learn: 0.5488714	total: 8.22s	remaining: 1m 12s
203:	learn: 0.5488329	total: 8.26s	remaining: 1m 12s
204:	learn: 0.5488132	total: 8.3s	remaining: 1m 12s
205:	learn: 0.5487610	total: 8.34s	remaining: 1m 12s
206:	learn: 0.5487268	total: 8.38s	remaining: 1m 12s
207:	learn: 0.5486940	total: 8.42s	remaining: 1m 12s
208:	learn: 0.5486665	total: 8.46s	remaining: 1m 12s
209:	learn: 0.5486277	total: 8.5s	remaining: 1m 12s
210:	learn: 0.5486092	total: 8.54s	remaining: 1m 12s
211:	learn: 0.5485739	total: 8.58s	remaining: 1m 12s
212:	learn: 0.5485300	total: 8.62s	remaining: 1m 12s
213:	learn: 0.5484938	total: 8.66s	remaining: 1m 12s
214:	learn: 0.5484780	total: 8.7s	remaining: 1m 12s
215:	learn: 0.5484557	total: 8.75s	remaining: 1m 12s
216:	learn: 0.5484237	total: 8.79s	remaining: 1m 12s
217:	learn: 0.5484028	total: 8.83s	remaining: 1m 12s
218:	learn: 0.5483819	total: 8.87s	remaining: 1m 12s
219:	learn: 0.5483585	total: 8.9s	remaining: 1m 12s
220:	learn: 0.5483431	total: 8.95s	remaining: 1m 12s
221:	learn: 0.5483192	total: 8.98s	remaining: 1m 11s
222:	learn: 0.5482968	total: 9.03s	remaining: 1m 11s
223:	learn: 0.5482858	total: 9.07s	remaining: 1m 11s
224:	learn: 0.5482481	total: 9.11s	remaining: 1m 11s
225:	learn: 0.5482245	total: 9.15s	remaining: 1m 11s
226:	learn: 0.5482122	total: 9.19s	remaining: 1m 11s
227:	learn: 0.5481948	total: 9.23s	remaining: 1m 11s
228:	learn: 0.5481737	total: 9.27s	remaining: 1m 11s
229:	learn: 0.5481516	total: 9.31s	remaining: 1m 11s
230:	learn: 0.5481092	total: 9.35s	remaining: 1m 11s
231:	learn: 0.5480955	total: 9.39s	remaining: 1m 11s
232:	learn: 0.5480764	total: 9.43s	remaining: 1m 11s
233:	learn: 0.5480406	total: 9.47s	remaining: 1m 11s
234:	learn: 0.5480172	total: 9.51s	remaining: 1m 11s
235:	learn: 0.5479784	total: 9.54s	remaining: 1m 11s
236:	learn: 0.5479609	total: 9.58s	remaining: 1m 11s
237:	learn: 0.5479414	total: 9.62s	remaining: 1m 11s
238:	learn: 0.5479261	total: 9.66s	remaining: 1m 11s
239:	learn: 0.5479125	total: 9.7s	remaining: 1m 11s
240:	learn: 0.5478809	total: 9.74s	remaining: 1m 11s
241:	learn: 0.5478687	total: 9.78s	remaining: 1m 11s
242:	learn: 0.5478484	total: 9.82s	remaining: 1m 11s
243:	learn: 0.5478209	total: 9.86s	remaining: 1m 10s
244:	learn: 0.5477932	total: 9.9s	remaining: 1m 10s
245:	learn: 0.5477859	total: 9.94s	remaining: 1m 10s
246:	learn: 0.5477711	total: 9.99s	remaining: 1m 10s
247:	learn: 0.5477479	total: 10s	remaining: 1m 10s
248:	learn: 0.5477307	total: 10.1s	remaining: 1m 10s
249:	learn: 0.5477180	total: 10.1s	remaining: 1m 10s
250:	learn: 0.5476971	total: 10.1s	remaining: 1m 10s
251:	learn: 0.5476746	total: 10.2s	remaining: 1m 10s
252:	learn: 0.5476618	total: 10.2s	remaining: 1m 10s
253:	learn: 0.5476451	total: 10.3s	remaining: 1m 10s
254:	learn: 0.5476383	total: 10.3s	remaining: 1m 10s
255:	learn: 0.5476265	total: 10.3s	remaining: 1m 10s
256:	learn: 0.5476123	total: 10.4s	remaining: 1m 10s
257:	learn: 0.5475886	total: 10.4s	remaining: 1m 10s
258:	learn: 0.5475673	total: 10.5s	remaining: 1m 10s
259:	learn: 0.5475538	total: 10.5s	remaining: 1m 10s
260:	learn: 0.5475247	total: 10.6s	remaining: 1m 10s
261:	learn: 0.5475015	total: 10.6s	remaining: 1m 10s
262:	learn: 0.5474865	total: 10.6s	remaining: 1m 10s
263:	learn: 0.5474640	total: 10.7s	remaining: 1m 10s
264:	learn: 0.5474255	total: 10.7s	remaining: 1m 10s
265:	learn: 0.5474125	total: 10.8s	remaining: 1m 10s
266:	learn: 0.5473923	total: 10.8s	remaining: 1m 10s
267:	learn: 0.5473512	total: 10.9s	remaining: 1m 10s
268:	learn: 0.5473325	total: 10.9s	remaining: 1m 10s
269:	learn: 0.5473136	total: 10.9s	remaining: 1m 10s
270:	learn: 0.5472877	total: 11s	remaining: 1m 10s
271:	learn: 0.5472794	total: 11s	remaining: 1m 9s
272:	learn: 0.5472741	total: 11.1s	remaining: 1m 9s
273:	learn: 0.5472514	total: 11.1s	remaining: 1m 9s
274:	learn: 0.5472359	total: 11.1s	remaining: 1m 9s
275:	learn: 0.5472222	total: 11.2s	remaining: 1m 9s
276:	learn: 0.5471826	total: 11.2s	remaining: 1m 9s
277:	learn: 0.5471802	total: 11.3s	remaining: 1m 9s
278:	learn: 0.5471673	total: 11.3s	remaining: 1m 9s
279:	learn: 0.5471378	total: 11.3s	remaining: 1m 9s
280:	learn: 0.5471352	total: 11.4s	remaining: 1m 9s
281:	learn: 0.5471124	total: 11.4s	remaining: 1m 9s
282:	learn: 0.5470938	total: 11.4s	remaining: 1m 9s
283:	learn: 0.5470739	total: 11.5s	remaining: 1m 9s
284:	learn: 0.5470594	total: 11.5s	remaining: 1m 9s
285:	learn: 0.5470400	total: 11.6s	remaining: 1m 9s
286:	learn: 0.5470243	total: 11.6s	remaining: 1m 9s
287:	learn: 0.5470174	total: 11.6s	remaining: 1m 9s
288:	learn: 0.5470062	total: 11.7s	remaining: 1m 9s
289:	learn: 0.5469919	total: 11.7s	remaining: 1m 9s
290:	learn: 0.5469793	total: 11.8s	remaining: 1m 9s
291:	learn: 0.5469726	total: 11.8s	remaining: 1m 9s
292:	learn: 0.5469583	total: 11.8s	remaining: 1m 9s
293:	learn: 0.5469554	total: 11.9s	remaining: 1m 8s
294:	learn: 0.5469392	total: 11.9s	remaining: 1m 8s
295:	learn: 0.5469238	total: 12s	remaining: 1m 8s
296:	learn: 0.5468874	total: 12s	remaining: 1m 8s
297:	learn: 0.5468581	total: 12.1s	remaining: 1m 8s
298:	learn: 0.5468496	total: 12.1s	remaining: 1m 8s
299:	learn: 0.5468445	total: 12.1s	remaining: 1m 8s
300:	learn: 0.5468335	total: 12.2s	remaining: 1m 8s
301:	learn: 0.5468071	total: 12.2s	remaining: 1m 8s
302:	learn: 0.5468011	total: 12.3s	remaining: 1m 8s
303:	learn: 0.5467987	total: 12.3s	remaining: 1m 8s
304:	learn: 0.5467828	total: 12.3s	remaining: 1m 8s
305:	learn: 0.5467763	total: 12.4s	remaining: 1m 8s
306:	learn: 0.5467719	total: 12.4s	remaining: 1m 8s
307:	learn: 0.5467638	total: 12.5s	remaining: 1m 8s
308:	learn: 0.5467311	total: 12.5s	remaining: 1m 8s
309:	learn: 0.5467181	total: 12.5s	remaining: 1m 8s
310:	learn: 0.5467088	total: 12.6s	remaining: 1m 8s
311:	learn: 0.5467034	total: 12.6s	remaining: 1m 8s
312:	learn: 0.5467004	total: 12.7s	remaining: 1m 8s
313:	learn: 0.5466858	total: 12.7s	remaining: 1m 8s
314:	learn: 0.5466720	total: 12.8s	remaining: 1m 8s
315:	learn: 0.5466573	total: 12.8s	remaining: 1m 8s
316:	learn: 0.5466453	total: 12.9s	remaining: 1m 8s
317:	learn: 0.5466291	total: 12.9s	remaining: 1m 8s
318:	learn: 0.5466186	total: 12.9s	remaining: 1m 8s
319:	learn: 0.5466040	total: 13s	remaining: 1m 8s
320:	learn: 0.5465705	total: 13s	remaining: 1m 8s
321:	learn: 0.5465339	total: 13.1s	remaining: 1m 8s
322:	learn: 0.5465255	total: 13.1s	remaining: 1m 8s
323:	learn: 0.5465143	total: 13.1s	remaining: 1m 7s
324:	learn: 0.5465032	total: 13.2s	remaining: 1m 7s
325:	learn: 0.5464808	total: 13.2s	remaining: 1m 7s
326:	learn: 0.5464674	total: 13.3s	remaining: 1m 7s
327:	learn: 0.5464638	total: 13.3s	remaining: 1m 7s
328:	learn: 0.5464605	total: 13.3s	remaining: 1m 7s
329:	learn: 0.5464411	total: 13.4s	remaining: 1m 7s
330:	learn: 0.5464222	total: 13.4s	remaining: 1m 7s
331:	learn: 0.5464115	total: 13.5s	remaining: 1m 7s
332:	learn: 0.5463927	total: 13.5s	remaining: 1m 7s
333:	learn: 0.5463766	total: 13.5s	remaining: 1m 7s
334:	learn: 0.5463671	total: 13.6s	remaining: 1m 7s
335:	learn: 0.5463520	total: 13.6s	remaining: 1m 7s
336:	learn: 0.5463390	total: 13.7s	remaining: 1m 7s
337:	learn: 0.5463216	total: 13.7s	remaining: 1m 7s
338:	learn: 0.5463104	total: 13.7s	remaining: 1m 7s
339:	learn: 0.5463080	total: 13.8s	remaining: 1m 7s
340:	learn: 0.5463017	total: 13.8s	remaining: 1m 7s
341:	learn: 0.5462844	total: 13.9s	remaining: 1m 7s
342:	learn: 0.5462803	total: 13.9s	remaining: 1m 7s
343:	learn: 0.5462476	total: 13.9s	remaining: 1m 7s
344:	learn: 0.5462312	total: 14s	remaining: 1m 7s
345:	learn: 0.5462241	total: 14s	remaining: 1m 7s
346:	learn: 0.5462222	total: 14.1s	remaining: 1m 6s
347:	learn: 0.5462189	total: 14.1s	remaining: 1m 6s
348:	learn: 0.5461972	total: 14.1s	remaining: 1m 6s
349:	learn: 0.5461831	total: 14.2s	remaining: 1m 6s
350:	learn: 0.5461669	total: 14.2s	remaining: 1m 6s
351:	learn: 0.5461560	total: 14.3s	remaining: 1m 6s
352:	learn: 0.5461364	total: 14.3s	remaining: 1m 6s
353:	learn: 0.5461270	total: 14.4s	remaining: 1m 6s
354:	learn: 0.5461018	total: 14.4s	remaining: 1m 6s
355:	learn: 0.5460998	total: 14.4s	remaining: 1m 6s
356:	learn: 0.5460788	total: 14.5s	remaining: 1m 6s
357:	learn: 0.5460731	total: 14.5s	remaining: 1m 6s
358:	learn: 0.5460519	total: 14.6s	remaining: 1m 6s
359:	learn: 0.5460316	total: 14.6s	remaining: 1m 6s
360:	learn: 0.5460226	total: 14.6s	remaining: 1m 6s
361:	learn: 0.5460205	total: 14.7s	remaining: 1m 6s
362:	learn: 0.5460111	total: 14.7s	remaining: 1m 6s
363:	learn: 0.5459957	total: 14.8s	remaining: 1m 6s
364:	learn: 0.5459843	total: 14.8s	remaining: 1m 6s
365:	learn: 0.5459686	total: 14.9s	remaining: 1m 6s
366:	learn: 0.5459659	total: 14.9s	remaining: 1m 6s
367:	learn: 0.5459639	total: 14.9s	remaining: 1m 6s
368:	learn: 0.5459439	total: 15s	remaining: 1m 6s
369:	learn: 0.5459405	total: 15s	remaining: 1m 6s
370:	learn: 0.5459246	total: 15s	remaining: 1m 6s
371:	learn: 0.5459196	total: 15.1s	remaining: 1m 6s
372:	learn: 0.5459168	total: 15.1s	remaining: 1m 5s
373:	learn: 0.5459128	total: 15.2s	remaining: 1m 5s
374:	learn: 0.5459072	total: 15.2s	remaining: 1m 5s
375:	learn: 0.5458831	total: 15.2s	remaining: 1m 5s
376:	learn: 0.5458741	total: 15.3s	remaining: 1m 5s
377:	learn: 0.5458535	total: 15.3s	remaining: 1m 5s
378:	learn: 0.5458492	total: 15.4s	remaining: 1m 5s
379:	learn: 0.5458465	total: 15.4s	remaining: 1m 5s
380:	learn: 0.5458439	total: 15.4s	remaining: 1m 5s

In [12]:
score = accuracy_score(y_test, y_pred)
score

0.719203187250996