In [23]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [24]:
dataset = pd.read_csv('ai_jobs_salaries_clean.csv')
dataset.head(5)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,experience_level_label,employment_type_label,work_mode,salary_outlier_flag,role_family,isco_group_hint
0,2025,EX,FT,Head of Data,348516,USD,348516,US,0,US,M,Executive-level,Full-time,On-site,True,Analytics Manager,Information and communications technology serv...
1,2025,EX,FT,Head of Data,232344,USD,232344,US,0,US,M,Executive-level,Full-time,On-site,False,Analytics Manager,Information and communications technology serv...
2,2025,SE,FT,Data Scientist,145400,USD,145400,US,0,US,M,Senior-level,Full-time,On-site,False,Data Scientist,"Mathematicians, actuaries and statisticians"
3,2025,SE,FT,Data Scientist,81600,USD,81600,US,0,US,M,Senior-level,Full-time,On-site,False,Data Scientist,"Mathematicians, actuaries and statisticians"
4,2025,MI,FT,Engineer,160000,USD,160000,US,100,US,M,Mid-level,Full-time,Remote,False,Other / Unclassified,NaN

In [25]:
dataset['High_Salary'] = (dataset['salary_in_usd'] >= 150000).astype(int)

leak_cols = [
    'High_Salary',
    'salary',
    'salary_currency',
    'salary_in_usd',
    'salary_outlier_flag',
]

In [26]:
print(dataset.isnull().sum())

work_year                     0
experience_level              0
employment_type               0
job_title                     0
salary                        0
salary_currency               0
salary_in_usd                 0
employee_residence            0
remote_ratio                  0
company_location              0
company_size                  0
experience_level_label        0
employment_type_label         0
work_mode                     0
salary_outlier_flag           0
role_family                   0
isco_group_hint           40540
High_Salary                   0
dtype: int64

In [27]:
dataset = dataset.dropna()

In [28]:
datatrain, datatest = train_test_split(dataset, test_size=0.2, shuffle=True)

In [29]:
X_train = datatrain.drop(columns=leak_cols)
y_train = datatrain['High_Salary']
X_test = datatest.drop(columns=leak_cols)
y_test = datatest['High_Salary']

In [30]:
X_train.head(5)

,work_year,experience_level,employment_type,job_title,employee_residence,remote_ratio,company_location,company_size,experience_level_label,employment_type_label,work_mode,role_family,isco_group_hint
23245,2025,SE,FT,Machine Learning Engineer,US,0,US,M,Senior-level,Full-time,On-site,ML Engineer,Software and applications developers
54769,2024,SE,FT,Data Engineer,US,0,US,M,Senior-level,Full-time,On-site,Data Engineer,Software and applications developers
29564,2025,SE,FT,Machine Learning Engineer,US,0,US,M,Senior-level,Full-time,On-site,ML Engineer,Software and applications developers
70903,2022,SE,FT,Data Analyst,US,0,US,M,Senior-level,Full-time,On-site,Data Analyst,Business services and administration managers
52638,2024,SE,FT,Data Scientist,CA,0,CA,M,Senior-level,Full-time,On-site,Data Scientist,"Mathematicians, actuaries and statisticians"

In [31]:
cols = ['experience_level', 'employment_type', 'job_title', 'employee_residence', 'company_location', 
        'company_size', 'experience_level_label', 'employment_type_label', 'work_mode', 'role_family', 'isco_group_hint']

In [32]:
from catboost import CatBoostClassifier
model = CatBoostClassifier(iterations=1000, cat_features=cols, task_type='GPU')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

Learning rate set to 0.028235
0:	learn: 0.6844244	total: 44.3ms	remaining: 44.3s
1:	learn: 0.6762385	total: 90.1ms	remaining: 45s
2:	learn: 0.6684313	total: 148ms	remaining: 49.2s
3:	learn: 0.6616562	total: 208ms	remaining: 51.7s
4:	learn: 0.6546229	total: 260ms	remaining: 51.8s
5:	learn: 0.6479076	total: 307ms	remaining: 50.9s
6:	learn: 0.6420579	total: 356ms	remaining: 50.5s
7:	learn: 0.6367741	total: 405ms	remaining: 50.3s
8:	learn: 0.6312500	total: 458ms	remaining: 50.4s
9:	learn: 0.6263341	total: 509ms	remaining: 50.4s
10:	learn: 0.6217445	total: 555ms	remaining: 49.9s
11:	learn: 0.6174473	total: 603ms	remaining: 49.7s
12:	learn: 0.6133319	total: 655ms	remaining: 49.7s
13:	learn: 0.6095718	total: 706ms	remaining: 49.7s
14:	learn: 0.6060709	total: 759ms	remaining: 49.8s
15:	learn: 0.6028829	total: 839ms	remaining: 51.6s
16:	learn: 0.5998037	total: 918ms	remaining: 53.1s
17:	learn: 0.5967117	total: 992ms	remaining: 54.1s
18:	learn: 0.5940896	total: 1.06s	remaining: 54.8s
19:	learn: 0.5915551	total: 1.13s	remaining: 55.3s
20:	learn: 0.5892837	total: 1.2s	remaining: 55.8s
21:	learn: 0.5872370	total: 1.27s	remaining: 56.3s
22:	learn: 0.5852714	total: 1.33s	remaining: 56.5s
23:	learn: 0.5832846	total: 1.4s	remaining: 57s
24:	learn: 0.5814349	total: 1.47s	remaining: 57.3s
25:	learn: 0.5797856	total: 1.57s	remaining: 58.9s
26:	learn: 0.5781408	total: 1.66s	remaining: 59.9s
27:	learn: 0.5765367	total: 1.74s	remaining: 1m
28:	learn: 0.5750905	total: 1.8s	remaining: 1m
29:	learn: 0.5737423	total: 1.87s	remaining: 1m
30:	learn: 0.5724544	total: 1.93s	remaining: 1m
31:	learn: 0.5712579	total: 2s	remaining: 1m
32:	learn: 0.5700716	total: 2.06s	remaining: 1m
33:	learn: 0.5689992	total: 2.13s	remaining: 1m
34:	learn: 0.5679955	total: 2.2s	remaining: 1m
35:	learn: 0.5670507	total: 2.27s	remaining: 1m
36:	learn: 0.5661496	total: 2.33s	remaining: 1m
37:	learn: 0.5653361	total: 2.39s	remaining: 1m
38:	learn: 0.5645589	total: 2.46s	remaining: 1m
39:	learn: 0.5636908	total: 2.52s	remaining: 1m
40:	learn: 0.5629149	total: 2.6s	remaining: 1m
41:	learn: 0.5621776	total: 2.68s	remaining: 1m 1s
42:	learn: 0.5615212	total: 2.75s	remaining: 1m 1s
43:	learn: 0.5609028	total: 2.82s	remaining: 1m 1s
44:	learn: 0.5603472	total: 2.88s	remaining: 1m 1s
45:	learn: 0.5598743	total: 2.95s	remaining: 1m 1s
46:	learn: 0.5593310	total: 3.02s	remaining: 1m 1s
47:	learn: 0.5588543	total: 3.09s	remaining: 1m 1s
48:	learn: 0.5584585	total: 3.16s	remaining: 1m 1s
49:	learn: 0.5580416	total: 3.23s	remaining: 1m 1s
50:	learn: 0.5576590	total: 3.3s	remaining: 1m 1s
51:	learn: 0.5572408	total: 3.36s	remaining: 1m 1s
52:	learn: 0.5568506	total: 3.42s	remaining: 1m 1s
53:	learn: 0.5565151	total: 3.49s	remaining: 1m 1s
54:	learn: 0.5562197	total: 3.55s	remaining: 1m 1s
55:	learn: 0.5559015	total: 3.63s	remaining: 1m 1s
56:	learn: 0.5555141	total: 3.69s	remaining: 1m 1s
57:	learn: 0.5552190	total: 3.75s	remaining: 1m
58:	learn: 0.5549496	total: 3.81s	remaining: 1m
59:	learn: 0.5547075	total: 3.88s	remaining: 1m
60:	learn: 0.5544574	total: 3.94s	remaining: 1m
61:	learn: 0.5542277	total: 4s	remaining: 1m
62:	learn: 0.5539843	total: 4.07s	remaining: 1m
63:	learn: 0.5537308	total: 4.14s	remaining: 1m
64:	learn: 0.5535590	total: 4.22s	remaining: 1m
65:	learn: 0.5533137	total: 4.3s	remaining: 1m
66:	learn: 0.5531244	total: 4.37s	remaining: 1m
67:	learn: 0.5529283	total: 4.45s	remaining: 1m
68:	learn: 0.5527561	total: 4.52s	remaining: 1m
69:	learn: 0.5525822	total: 4.58s	remaining: 1m
70:	learn: 0.5524394	total: 4.65s	remaining: 1m
71:	learn: 0.5523017	total: 4.71s	remaining: 1m
72:	learn: 0.5521566	total: 4.79s	remaining: 1m
73:	learn: 0.5520288	total: 4.86s	remaining: 1m
74:	learn: 0.5518760	total: 4.94s	remaining: 1m
75:	learn: 0.5517310	total: 5s	remaining: 1m
76:	learn: 0.5515802	total: 5.07s	remaining: 1m
77:	learn: 0.5514184	total: 5.13s	remaining: 1m
78:	learn: 0.5512733	total: 5.19s	remaining: 1m
79:	learn: 0.5511674	total: 5.26s	remaining: 1m
80:	learn: 0.5510183	total: 5.32s	remaining: 1m
81:	learn: 0.5509100	total: 5.39s	remaining: 1m
82:	learn: 0.5508033	total: 5.45s	remaining: 1m
83:	learn: 0.5507144	total: 5.52s	remaining: 1m
84:	learn: 0.5506168	total: 5.61s	remaining: 1m
85:	learn: 0.5504944	total: 5.69s	remaining: 1m
86:	learn: 0.5504020	total: 5.75s	remaining: 1m
87:	learn: 0.5502591	total: 5.81s	remaining: 1m
88:	learn: 0.5501564	total: 5.88s	remaining: 1m
89:	learn: 0.5500555	total: 5.98s	remaining: 1m
90:	learn: 0.5499692	total: 6.05s	remaining: 1m
91:	learn: 0.5498850	total: 6.13s	remaining: 1m
92:	learn: 0.5498022	total: 6.21s	remaining: 1m
93:	learn: 0.5497370	total: 6.28s	remaining: 1m
94:	learn: 0.5496754	total: 6.36s	remaining: 1m
95:	learn: 0.5495533	total: 6.43s	remaining: 1m
96:	learn: 0.5494712	total: 6.51s	remaining: 1m
97:	learn: 0.5493925	total: 6.6s	remaining: 1m
98:	learn: 0.5493277	total: 6.67s	remaining: 1m
99:	learn: 0.5492827	total: 6.74s	remaining: 1m
100:	learn: 0.5492206	total: 6.8s	remaining: 1m
101:	learn: 0.5491553	total: 6.86s	remaining: 1m
102:	learn: 0.5490901	total: 6.93s	remaining: 1m
103:	learn: 0.5490235	total: 7s	remaining: 1m
104:	learn: 0.5489664	total: 7.08s	remaining: 1m
105:	learn: 0.5489070	total: 7.15s	remaining: 1m
106:	learn: 0.5488109	total: 7.23s	remaining: 1m
107:	learn: 0.5487543	total: 7.31s	remaining: 1m
108:	learn: 0.5486986	total: 7.39s	remaining: 1m
109:	learn: 0.5486216	total: 7.46s	remaining: 1m
110:	learn: 0.5485724	total: 7.54s	remaining: 1m
111:	learn: 0.5485365	total: 7.62s	remaining: 1m
112:	learn: 0.5484762	total: 7.69s	remaining: 1m
113:	learn: 0.5484044	total: 7.77s	remaining: 1m
114:	learn: 0.5483456	total: 7.85s	remaining: 1m
115:	learn: 0.5482857	total: 7.93s	remaining: 1m
116:	learn: 0.5482387	total: 8s	remaining: 1m
117:	learn: 0.5481896	total: 8.06s	remaining: 1m
118:	learn: 0.5481481	total: 8.14s	remaining: 1m
119:	learn: 0.5480961	total: 8.21s	remaining: 1m
120:	learn: 0.5480339	total: 8.29s	remaining: 1m
121:	learn: 0.5479915	total: 8.36s	remaining: 1m
122:	learn: 0.5479449	total: 8.44s	remaining: 1m
123:	learn: 0.5479018	total: 8.52s	remaining: 1m
124:	learn: 0.5478710	total: 8.59s	remaining: 1m
125:	learn: 0.5478165	total: 8.67s	remaining: 1m
126:	learn: 0.5477970	total: 8.75s	remaining: 1m
127:	learn: 0.5477555	total: 8.83s	remaining: 1m
128:	learn: 0.5476930	total: 8.9s	remaining: 1m
129:	learn: 0.5476479	total: 8.97s	remaining: 1m
130:	learn: 0.5475967	total: 9.05s	remaining: 1m
131:	learn: 0.5475578	total: 9.13s	remaining: 1m
132:	learn: 0.5475226	total: 9.21s	remaining: 1m
133:	learn: 0.5474903	total: 9.29s	remaining: 1m
134:	learn: 0.5474457	total: 9.37s	remaining: 1m
135:	learn: 0.5473909	total: 9.45s	remaining: 1m
136:	learn: 0.5473485	total: 9.51s	remaining: 59.9s
137:	learn: 0.5473371	total: 9.58s	remaining: 59.9s
138:	learn: 0.5472730	total: 9.66s	remaining: 59.8s
139:	learn: 0.5472294	total: 9.74s	remaining: 59.8s
140:	learn: 0.5471769	total: 9.82s	remaining: 59.8s
141:	learn: 0.5471425	total: 9.89s	remaining: 59.8s
142:	learn: 0.5471125	total: 9.97s	remaining: 59.8s
143:	learn: 0.5470911	total: 10s	remaining: 59.7s
144:	learn: 0.5470711	total: 10.1s	remaining: 59.6s
145:	learn: 0.5470411	total: 10.2s	remaining: 59.6s
146:	learn: 0.5470232	total: 10.3s	remaining: 59.7s
147:	learn: 0.5469544	total: 10.3s	remaining: 59.6s
148:	learn: 0.5469256	total: 10.4s	remaining: 59.5s
149:	learn: 0.5468861	total: 10.5s	remaining: 59.5s
150:	learn: 0.5468511	total: 10.6s	remaining: 59.4s
151:	learn: 0.5468204	total: 10.7s	remaining: 59.4s
152:	learn: 0.5467827	total: 10.7s	remaining: 59.4s
153:	learn: 0.5467663	total: 10.8s	remaining: 59.3s
154:	learn: 0.5467107	total: 10.9s	remaining: 59.3s
155:	learn: 0.5466598	total: 10.9s	remaining: 59.2s
156:	learn: 0.5466184	total: 11s	remaining: 59.1s
157:	learn: 0.5465737	total: 11.1s	remaining: 59s
158:	learn: 0.5465687	total: 11.1s	remaining: 58.9s
159:	learn: 0.5465198	total: 11.2s	remaining: 58.9s
160:	learn: 0.5465180	total: 11.3s	remaining: 58.8s
161:	learn: 0.5464914	total: 11.4s	remaining: 58.8s
162:	learn: 0.5464676	total: 11.4s	remaining: 58.8s
163:	learn: 0.5464589	total: 11.5s	remaining: 58.7s
164:	learn: 0.5464260	total: 11.6s	remaining: 58.6s
165:	learn: 0.5464049	total: 11.7s	remaining: 58.5s
166:	learn: 0.5463602	total: 11.7s	remaining: 58.4s
167:	learn: 0.5463589	total: 11.8s	remaining: 58.3s
168:	learn: 0.5463499	total: 11.8s	remaining: 58.2s
169:	learn: 0.5463477	total: 11.9s	remaining: 58.2s
170:	learn: 0.5463452	total: 12s	remaining: 58.1s
171:	learn: 0.5463219	total: 12.1s	remaining: 58.1s
172:	learn: 0.5462621	total: 12.2s	remaining: 58.1s
173:	learn: 0.5462479	total: 12.2s	remaining: 58.1s
174:	learn: 0.5461929	total: 12.3s	remaining: 57.9s
175:	learn: 0.5461661	total: 12.4s	remaining: 58s
176:	learn: 0.5461236	total: 12.4s	remaining: 57.9s
177:	learn: 0.5461021	total: 12.5s	remaining: 57.8s
178:	learn: 0.5460886	total: 12.6s	remaining: 57.8s
179:	learn: 0.5460608	total: 12.7s	remaining: 57.7s
180:	learn: 0.5460117	total: 12.7s	remaining: 57.7s
181:	learn: 0.5459906	total: 12.8s	remaining: 57.7s
182:	learn: 0.5459614	total: 12.9s	remaining: 57.6s
183:	learn: 0.5459465	total: 13s	remaining: 57.6s
184:	learn: 0.5458938	total: 13.1s	remaining: 57.6s
185:	learn: 0.5458923	total: 13.1s	remaining: 57.5s
186:	learn: 0.5458662	total: 13.2s	remaining: 57.5s
187:	learn: 0.5458495	total: 13.3s	remaining: 57.5s
188:	learn: 0.5458375	total: 13.4s	remaining: 57.4s
189:	learn: 0.5458324	total: 13.5s	remaining: 57.4s
190:	learn: 0.5457970	total: 13.5s	remaining: 57.3s
191:	learn: 0.5457929	total: 13.6s	remaining: 57.3s
192:	learn: 0.5457923	total: 13.7s	remaining: 57.2s
193:	learn: 0.5457485	total: 13.8s	remaining: 57.2s
194:	learn: 0.5456981	total: 13.9s	remaining: 57.2s
195:	learn: 0.5456696	total: 13.9s	remaining: 57.2s
196:	learn: 0.5456411	total: 14s	remaining: 57.1s
197:	learn: 0.5456316	total: 14.1s	remaining: 57.1s
198:	learn: 0.5456296	total: 14.2s	remaining: 57s
199:	learn: 0.5456061	total: 14.3s	remaining: 57s
200:	learn: 0.5455735	total: 14.3s	remaining: 57s
201:	learn: 0.5455560	total: 14.4s	remaining: 56.9s
202:	learn: 0.5455547	total: 14.5s	remaining: 57s
203:	learn: 0.5455037	total: 14.6s	remaining: 56.8s
204:	learn: 0.5455026	total: 14.6s	remaining: 56.8s
205:	learn: 0.5454754	total: 14.7s	remaining: 56.7s
206:	learn: 0.5454572	total: 14.8s	remaining: 56.7s
207:	learn: 0.5454393	total: 14.9s	remaining: 56.6s
208:	learn: 0.5454063	total: 14.9s	remaining: 56.5s
209:	learn: 0.5454051	total: 15s	remaining: 56.4s
210:	learn: 0.5454046	total: 15.1s	remaining: 56.3s
211:	learn: 0.5453878	total: 15.1s	remaining: 56.2s
212:	learn: 0.5453734	total: 15.2s	remaining: 56.1s
213:	learn: 0.5453728	total: 15.2s	remaining: 56s
214:	learn: 0.5453517	total: 15.3s	remaining: 55.9s
215:	learn: 0.5453141	total: 15.4s	remaining: 55.8s
216:	learn: 0.5453130	total: 15.4s	remaining: 55.7s
217:	learn: 0.5453063	total: 15.5s	remaining: 55.6s
218:	learn: 0.5453060	total: 15.6s	remaining: 55.5s
219:	learn: 0.5452834	total: 15.6s	remaining: 55.4s
220:	learn: 0.5452769	total: 15.7s	remaining: 55.3s
221:	learn: 0.5452689	total: 15.8s	remaining: 55.2s
222:	learn: 0.5452527	total: 15.8s	remaining: 55.2s
223:	learn: 0.5452517	total: 15.9s	remaining: 55.1s
224:	learn: 0.5452508	total: 16s	remaining: 55s
225:	learn: 0.5452455	total: 16s	remaining: 55s
226:	learn: 0.5452444	total: 16.1s	remaining: 54.9s
227:	learn: 0.5452166	total: 16.2s	remaining: 54.8s
228:	learn: 0.5451995	total: 16.3s	remaining: 54.8s
229:	learn: 0.5451991	total: 16.3s	remaining: 54.6s
230:	learn: 0.5451982	total: 16.4s	remaining: 54.6s
231:	learn: 0.5451481	total: 16.5s	remaining: 54.5s
232:	learn: 0.5451456	total: 16.6s	remaining: 54.5s
233:	learn: 0.5451149	total: 16.6s	remaining: 54.4s
234:	learn: 0.5451062	total: 16.7s	remaining: 54.4s
235:	learn: 0.5451032	total: 16.8s	remaining: 54.3s
236:	learn: 0.5450681	total: 16.9s	remaining: 54.3s
237:	learn: 0.5450677	total: 16.9s	remaining: 54.2s
238:	learn: 0.5450667	total: 17s	remaining: 54.1s
239:	learn: 0.5450663	total: 17.1s	remaining: 54.1s
240:	learn: 0.5450613	total: 17.2s	remaining: 54.1s
241:	learn: 0.5450595	total: 17.2s	remaining: 54s
242:	learn: 0.5450544	total: 17.3s	remaining: 53.9s
243:	learn: 0.5450319	total: 17.4s	remaining: 53.8s
244:	learn: 0.5450050	total: 17.4s	remaining: 53.8s
245:	learn: 0.5449803	total: 17.5s	remaining: 53.7s
246:	learn: 0.5449638	total: 17.6s	remaining: 53.7s
247:	learn: 0.5449614	total: 17.7s	remaining: 53.6s
248:	learn: 0.5449560	total: 17.8s	remaining: 53.6s
249:	learn: 0.5449553	total: 17.8s	remaining: 53.5s
250:	learn: 0.5449460	total: 17.9s	remaining: 53.4s
251:	learn: 0.5449243	total: 18s	remaining: 53.4s
252:	learn: 0.5448961	total: 18.1s	remaining: 53.3s
253:	learn: 0.5448931	total: 18.1s	remaining: 53.3s
254:	learn: 0.5448709	total: 18.2s	remaining: 53.2s
255:	learn: 0.5448651	total: 18.3s	remaining: 53.2s
256:	learn: 0.5448490	total: 18.4s	remaining: 53.1s
257:	learn: 0.5448481	total: 18.4s	remaining: 53s
258:	learn: 0.5448338	total: 18.5s	remaining: 52.9s
259:	learn: 0.5448316	total: 18.6s	remaining: 52.9s
260:	learn: 0.5448211	total: 18.7s	remaining: 52.9s
261:	learn: 0.5448199	total: 18.7s	remaining: 52.8s
262:	learn: 0.5448195	total: 18.8s	remaining: 52.7s
263:	learn: 0.5447763	total: 18.9s	remaining: 52.6s
264:	learn: 0.5447750	total: 19s	remaining: 52.6s
265:	learn: 0.5447730	total: 19s	remaining: 52.5s
266:	learn: 0.5447686	total: 19.1s	remaining: 52.4s
267:	learn: 0.5447683	total: 19.2s	remaining: 52.3s
268:	learn: 0.5447592	total: 19.2s	remaining: 52.3s
269:	learn: 0.5447316	total: 19.3s	remaining: 52.2s
270:	learn: 0.5447226	total: 19.4s	remaining: 52.2s
271:	learn: 0.5447188	total: 19.5s	remaining: 52.1s
272:	learn: 0.5447167	total: 19.5s	remaining: 52s
273:	learn: 0.5447154	total: 19.6s	remaining: 51.9s
274:	learn: 0.5447021	total: 19.7s	remaining: 51.8s
275:	learn: 0.5447004	total: 19.7s	remaining: 51.7s
276:	learn: 0.5446904	total: 19.8s	remaining: 51.7s
277:	learn: 0.5446454	total: 19.9s	remaining: 51.6s
278:	learn: 0.5446334	total: 19.9s	remaining: 51.5s
279:	learn: 0.5446313	total: 20s	remaining: 51.5s
280:	learn: 0.5446308	total: 20.1s	remaining: 51.4s
281:	learn: 0.5446265	total: 20.2s	remaining: 51.4s
282:	learn: 0.5446032	total: 20.3s	remaining: 51.3s
283:	learn: 0.5445915	total: 20.3s	remaining: 51.3s
284:	learn: 0.5445641	total: 20.4s	remaining: 51.2s
285:	learn: 0.5445568	total: 20.5s	remaining: 51.1s
286:	learn: 0.5445562	total: 20.6s	remaining: 51.1s
287:	learn: 0.5445390	total: 20.6s	remaining: 51s
288:	learn: 0.5445124	total: 20.7s	remaining: 50.9s
289:	learn: 0.5445113	total: 20.8s	remaining: 50.9s
290:	learn: 0.5445009	total: 20.8s	remaining: 50.8s
291:	learn: 0.5444990	total: 20.9s	remaining: 50.7s
292:	learn: 0.5444897	total: 21s	remaining: 50.7s
293:	learn: 0.5444846	total: 21.1s	remaining: 50.6s
294:	learn: 0.5444393	total: 21.2s	remaining: 50.6s
295:	learn: 0.5444222	total: 21.2s	remaining: 50.5s
296:	learn: 0.5444210	total: 21.3s	remaining: 50.4s
297:	learn: 0.5444066	total: 21.4s	remaining: 50.4s
298:	learn: 0.5443772	total: 21.5s	remaining: 50.4s
299:	learn: 0.5443743	total: 21.6s	remaining: 50.3s
300:	learn: 0.5443743	total: 21.6s	remaining: 50.2s
301:	learn: 0.5443578	total: 21.7s	remaining: 50.3s
302:	learn: 0.5443562	total: 21.8s	remaining: 50.2s
303:	learn: 0.5443527	total: 21.9s	remaining: 50.1s
304:	learn: 0.5443335	total: 22s	remaining: 50.1s
305:	learn: 0.5443157	total: 22s	remaining: 50s
306:	learn: 0.5442883	total: 22.1s	remaining: 50s
307:	learn: 0.5442688	total: 22.2s	remaining: 49.9s
308:	learn: 0.5442681	total: 22.3s	remaining: 49.8s
309:	learn: 0.5442627	total: 22.4s	remaining: 49.8s
310:	learn: 0.5442592	total: 22.4s	remaining: 49.7s
311:	learn: 0.5442573	total: 22.5s	remaining: 49.7s
312:	learn: 0.5442542	total: 22.6s	remaining: 49.6s
313:	learn: 0.5442388	total: 22.7s	remaining: 49.5s
314:	learn: 0.5442376	total: 22.7s	remaining: 49.4s
315:	learn: 0.5442108	total: 22.8s	remaining: 49.4s
316:	learn: 0.5442097	total: 22.9s	remaining: 49.3s
317:	learn: 0.5442067	total: 23s	remaining: 49.2s
318:	learn: 0.5442059	total: 23s	remaining: 49.1s
319:	learn: 0.5441731	total: 23.1s	remaining: 49.1s
320:	learn: 0.5441724	total: 23.2s	remaining: 49.1s
321:	learn: 0.5441583	total: 23.3s	remaining: 49s
322:	learn: 0.5441336	total: 23.3s	remaining: 48.9s
323:	learn: 0.5441214	total: 23.4s	remaining: 48.9s
324:	learn: 0.5441171	total: 23.5s	remaining: 48.8s
325:	learn: 0.5441157	total: 23.6s	remaining: 48.7s
326:	learn: 0.5441066	total: 23.6s	remaining: 48.7s
327:	learn: 0.5441036	total: 23.7s	remaining: 48.6s
328:	learn: 0.5440994	total: 23.8s	remaining: 48.5s
329:	learn: 0.5440978	total: 23.9s	remaining: 48.5s
330:	learn: 0.5440976	total: 23.9s	remaining: 48.4s
331:	learn: 0.5440960	total: 24s	remaining: 48.3s
332:	learn: 0.5440816	total: 24.1s	remaining: 48.2s
333:	learn: 0.5440745	total: 24.1s	remaining: 48.1s
334:	learn: 0.5440568	total: 24.2s	remaining: 48s
335:	learn: 0.5440486	total: 24.3s	remaining: 48s
336:	learn: 0.5440208	total: 24.4s	remaining: 47.9s
337:	learn: 0.5440009	total: 24.4s	remaining: 47.8s
338:	learn: 0.5439758	total: 24.5s	remaining: 47.8s
339:	learn: 0.5439739	total: 24.6s	remaining: 47.7s
340:	learn: 0.5439716	total: 24.7s	remaining: 47.6s
341:	learn: 0.5439577	total: 24.7s	remaining: 47.6s
342:	learn: 0.5439543	total: 24.8s	remaining: 47.6s
343:	learn: 0.5439490	total: 24.9s	remaining: 47.5s
344:	learn: 0.5439456	total: 25s	remaining: 47.4s
345:	learn: 0.5439329	total: 25s	remaining: 47.3s
346:	learn: 0.5438845	total: 25.1s	remaining: 47.3s
347:	learn: 0.5438840	total: 25.2s	remaining: 47.2s
348:	learn: 0.5438794	total: 25.3s	remaining: 47.1s
349:	learn: 0.5438773	total: 25.3s	remaining: 47s
350:	learn: 0.5438760	total: 25.4s	remaining: 47s
351:	learn: 0.5438760	total: 25.5s	remaining: 46.9s
352:	learn: 0.5438638	total: 25.6s	remaining: 46.9s
353:	learn: 0.5438494	total: 25.6s	remaining: 46.8s
354:	learn: 0.5438393	total: 25.7s	remaining: 46.7s
355:	learn: 0.5438373	total: 25.8s	remaining: 46.7s
356:	learn: 0.5438289	total: 25.9s	remaining: 46.6s
357:	learn: 0.5438250	total: 26s	remaining: 46.6s
358:	learn: 0.5438243	total: 26s	remaining: 46.5s
359:	learn: 0.5438231	total: 26.1s	remaining: 46.4s
360:	learn: 0.5437875	total: 26.2s	remaining: 46.3s
361:	learn: 0.5437839	total: 26.3s	remaining: 46.3s
362:	learn: 0.5437834	total: 26.3s	remaining: 46.2s
363:	learn: 0.5437803	total: 26.4s	remaining: 46.1s
364:	learn: 0.5437781	total: 26.4s	remaining: 46s
365:	learn: 0.5437778	total: 26.5s	remaining: 45.9s
366:	learn: 0.5437715	total: 26.6s	remaining: 45.9s
367:	learn: 0.5437696	total: 26.7s	remaining: 45.8s
368:	learn: 0.5437597	total: 26.8s	remaining: 45.7s
369:	learn: 0.5437385	total: 26.8s	remaining: 45.7s
370:	learn: 0.5437377	total: 26.9s	remaining: 45.6s
371:	learn: 0.5437174	total: 27s	remaining: 45.6s
372:	learn: 0.5437122	total: 27.1s	remaining: 45.5s
373:	learn: 0.5437122	total: 27.1s	remaining: 45.4s
374:	learn: 0.5437117	total: 27.2s	remaining: 45.3s
375:	learn: 0.5436920	total: 27.3s	remaining: 45.3s
376:	learn: 0.5436787	total: 27.3s	remaining: 45.2s
377:	learn: 0.5436558	total: 27.4s	remaining: 45.1s
378:	learn: 0.5436520	total: 27.5s	remaining: 45s
379:	learn: 0.5436471	total: 27.6s	remaining: 45s
380:	learn: 0.5436464	total: 27.6s	remaining: 44.9s
381:	learn: 0.5436429	total: 27.7s	remaining: 44.8s
382:	learn: 0.5436403	total: 27.8s	remaining: 44.8s
383:	learn: 0.5436108	total: 27.9s	remaining: 44.7s
384:	learn: 0.5436093	total: 27.9s	remaining: 44.6s
385:	learn: 0.5436031	total: 28s	remaining: 44.6s
386:	learn: 0.5435983	total: 28.1s	remaining: 44.5s
387:	learn: 0.5435982	total: 28.2s	remaining: 44.4s
388:	learn: 0.5435973	total: 28.2s	remaining: 44.4s
389:	learn: 0.5435918	total: 28.3s	remaining: 44.3s
390:	learn: 0.5435918	total: 28.4s	remaining: 44.2s
391:	learn: 0.5435885	total: 28.4s	remaining: 44.1s
392:	learn: 0.5435844	total: 28.5s	remaining: 44s

In [33]:
score = accuracy_score(y_test, y_pred)
score

0.7129880478087649